import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))

import pygame
from tile_palette import TilePalette
from Engine import utility
import tile_panel
import gui_tools

class MenuPanel(tile_panel.TilePanel):
   """
   A class for holding information to be written to a pygame.Surface
   Information is a rectangular grid of tiles, generated by a passed-in TilePalette.
   """
   
   def __init__(self, tile_palette, tiles_wide, tiles_tall):
      """
      Initializer
      tile_palette (TilePalette): palette used for creating tiles. Retained for future use.
      tiles_wide (int): width in tiles of the grid
      tiles_tall (int): height in tiles of the grid
      returns -> self
      """
      super().__init__(tile_palette, tiles_wide, tiles_tall)
      self.selected_index = 0
      self.string_list = []
      self.item_list = []
      self.menu_origin = (5, 2)
      self.selected_color = (0, 0, 127)
      self.max_str_len = 10
      self.selected_icon = 16 # right-pointing arrow
   
   def increment_selected(self):
      self.selected_index += 1
      if self.selected_index == len(self.string_list):
         self.selected_index = 0
   
   def decrement_selected(self):
      self.selected_index -= 1
      if self.selected_index == -1:
         self.selected_index = len(self.string_list) - 1
   
   def set_items(self, item_list):
      self.selected_index = 0
      self.string_list = []
      self.item_list = []
      self.max_str_len = 0
      for item in item_list:
         self.item_list.append(item)
         new_str = ""
         if isinstance(item, str):
            new_str = item
         elif hasattr(item, "get_menu_name"):
            new_str = item.get_menu_name()
         else:
            new_str = str(item)
         self.string_list.append(new_str)
         if len(new_str) > self.max_str_len:
            self.max_str_len = len(new_str)
      self.max_str_len += 3
      print(self.string_list)
   
   def get_image(self, size):
      """
      Returns the full panel image, scaled to the specified size
      size (int tuple): size of returned Surface
      returns -> Surface
      """
      y = self.menu_origin[1]
      self.set_rect_bg(self.menu_origin[0], self.menu_origin[1], self.max_str_len, len(self.string_list), self.background_color)
      if len(self.string_list) > 0:
         for str in self.string_list:
            self.write(self.menu_origin[0], y, self.max_str_len, 1, "  " + str)
            y += 1
      self.set_rect_bg(self.menu_origin[0], self.menu_origin[1] + self.selected_index, self.max_str_len, 1, self.selected_color)
      self.set_tile_index(self.menu_origin[0], self.menu_origin[1] + self.selected_index, self.selected_icon)
      
      return super().get_image(size)
      
# testing
if __name__ == "__main__":
   pygame.init()
   screen = pygame.display.set_mode((8 * 80, 16 * 24), pygame.SCALED | pygame.RESIZABLE)
   pygame.display.set_caption("MenuPanel Test")
   test_palette = TilePalette("WSFont_8x16.png", (16, 16), (8, 16))
   test_panel = MenuPanel(test_palette, 80, 24)
   
   background = pygame.Surface(screen.get_size())
   background = background.convert()
   background.fill((64, 64, 64))
   screen.blit(background, (0, 0))
   pygame.display.flip()
   clock = pygame.time.Clock()
   
   class SecondItem:
      def get_menu_name(self):
         return "Second"
   
   item_list = ["First", SecondItem(), "Third", 4, "Fifth"]
   test_panel.set_items(item_list)
   
   border_arr = utility.create_2d_array(test_panel.tiles_wide, test_panel.tiles_tall, False)
   border_arr = gui_tools.get_border_index_array(border_arr)
   for x in range(test_panel.tiles_wide):
      for y in range(test_panel.tiles_tall):
         if border_arr[x][y] != 0:
            test_panel.set_tile_index(x, y, border_arr[x][y])
   
   # Main Loop
   going = True
   while going:
      clock.tick(60)

      # Handle Input Events
      for event in pygame.event.get():
         if event.type == pygame.QUIT:
            going = False
         elif event.type == pygame.VIDEORESIZE:
            screen = pygame.display.set_mode((event.w, event.h), pygame.RESIZABLE) # don't put SCALED here or the user can't shrink the window
         # key input
         elif event.type == pygame.KEYDOWN :
            if event.key == pygame.K_ESCAPE:
               going = False
            elif event.key == pygame.K_DOWN or event.key == pygame.K_KP2:
               test_panel.increment_selected()
            elif event.key == pygame.K_UP or event.key == pygame.K_KP8:
               test_panel.decrement_selected()
      
      # Draw Everything
      screen.blit(background, (0, 0))
      screen.blit(test_panel.get_image(screen.get_size()), (0, 0))
      pygame.display.flip()
   pygame.quit()
